### PR TITLE
Break classes into individual files, replace background commands with process

### PR DESCRIPTION
**Pull request by slacrherbst**
This PR includes changes from #18. Compare against rogue-apps branch for supplemental changes.

First change is to break python files with multiple class definitions into multiple files. Second change is to replace background commands with Process devices.

### CODE REVIEW

**Comment by jmdewart** [comment]
There are more commands that aren't broken out - should they all be in proceeses/separate files now?

https://github.com/slaclab/cryo-det/blob/rogue-apps2/firmware/python/DspCoreLib/CryoDetCmbHcd/CryoChannels.py#L395-L443

Also there are command/processes that rely on LocalVariables as input parameters.  Now the processes are not self contained.  Maybe this is intended as some LocalVariables are shared between processes?

https://github.com/slaclab/cryo-det/blob/rogue-apps2/firmware/python/DspCoreLib/CryoDetCmbHcd/CryoChannels.py#L283-L330

https://github.com/slaclab/cryo-det/blob/rogue-apps2/firmware/python/DspCoreLib/CryoDetCmbHcd/SerialGradientDescent.py#L56-L62

**Comment by slacrherbst** [comment]
For now I focused on the commands that were previously background processes. If there are other commands that take time to run then we should consider moving them into Process. My worry is if scripts were setup to wait for the command to return to determine if the operation had completed. runEtaScan was a potential candidate, but it was a blocking command so I was not yet sure if I should move it. We may need to modify the calling scripts as we move some commands into Processes.

As for the local variables... ideally all of the configurations for a process should be contained in the process, as well as the running status variables. Here my goal was to, at least initially, be compatible with the existing set of variables so that the moving to a process device does not impact the current set of scripts. Over time we can modify this once we get a handle on the pysmurf side of things. All changes being incremental.

If we move runEtaScan into a Process as well the etaScanInProgress variable could become a link variable which reflects the logical or of the 'Running' variable of the set of Process devices. But maybe that variable just goes away eventually as we modify the calling scripts in pysmurf.

**Comment by slacrherbst** [comment]
Additional reorganization has been added to line up with organization decisions made in the Thursday meeting.

**Comment by slacrherbst** [comment]
Closing as this is no longer relevant.

**Pull request closed without merging**
